# Generated by Django 5.0 on 2024-05-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('nivel', models.CharField(choices=[('FACIL', 'FACIL'), ('MEDIO', 'MEDIO'), ('DIFICIL', 'DIFICIL')], default='FACIL', max_length=20)),
                ('tamanho', models.CharField(choices=[('GRANDE', 'GRANDE'), ('MEDIO', 'MEDIO'), ('PEQUENA', 'PEQUENA')], default='GRANDE', max_length=20)),
            ],
        ),
    ]
