# Generated by Django 5.0.6 on 2024-05-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='word',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='word',
            name='tamanho',
        ),
        migrations.AddField(
            model_name='word',
            name='content',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='senha',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
