# Generated by Django 5.0.6 on 2024-05-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_player_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='senha',
        ),
    ]
