# Generated by Django 5.0.6 on 2024-05-27 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_player_senha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
