# Generated by Django 5.0.6 on 2024-05-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palavra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='word',
        ),
    ]
