# Generated by Django 5.0.6 on 2024-05-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_palavra_delete_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palavra',
            name='palavra',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
